services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 10s ; python3 ./signalsApi.py"
    depends_on:
      - mysql

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'signals_db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
